package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entities generated by hbm2java
 */
@Entity
@Table(name = "entities", catalog = "agency")
public class Entities implements java.io.Serializable {

    private Integer id;
    private EntityTypes entityTypes;
    private EntityClass entityClass;
    private Set<EntityPrices> entityPriceses = new HashSet<EntityPrices>(0);
    private Set<Activities> activitieses = new HashSet<Activities>(0);

    public Entities() {
    }

    public Entities(EntityTypes entityTypes, EntityClass entityClass) {
        this.entityTypes = entityTypes;
        this.entityClass = entityClass;
    }

    public Entities(EntityTypes entityTypes, EntityClass entityClass,
            Set<EntityPrices> entityPriceses, Set<Activities> activitieses) {
        this.entityTypes = entityTypes;
        this.entityClass = entityClass;
        this.entityPriceses = entityPriceses;
        this.activitieses = activitieses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "entity_type_id", nullable = false)
    public EntityTypes getEntityTypes() {
        return this.entityTypes;
    }

    public void setEntityTypes(EntityTypes entityTypes) {
        this.entityTypes = entityTypes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "entity_class_id", nullable = false)
    public EntityClass getEntityClass() {
        return this.entityClass;
    }

    public void setEntityClass(EntityClass entityClass) {
        this.entityClass = entityClass;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entities")
    public Set<EntityPrices> getEntityPriceses() {
        return this.entityPriceses;
    }

    public void setEntityPriceses(Set<EntityPrices> entityPriceses) {
        this.entityPriceses = entityPriceses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entities")
    public Set<Activities> getActivitieses() {
        return this.activitieses;
    }

    public void setActivitieses(Set<Activities> activitieses) {
        this.activitieses = activitieses;
    }

}
