package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntityTypes generated by hbm2java
 */
@Entity
@Table(name = "entity_types", catalog = "agency")
public class EntityTypes  extends BaseEntity<Integer> implements java.io.Serializable, IEntity<Integer> {

    private String name;
    private Set<Entities> entitieses = new HashSet<Entities>(0);

    public EntityTypes() {
    }

    public EntityTypes(Integer id) {
        this.id = id;
    }

    public EntityTypes(String name) {
        this.name = name;
    }

    public EntityTypes(String name, Set<Entities> entitieses) {
        this.name = name;
        this.entitieses = entitieses;
    }

    @Column(name = "name", nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entityTypes")
    public Set<Entities> getEntitieses() {
        return this.entitieses;
    }

    public void setEntitieses(Set<Entities> entitieses) {
        this.entitieses = entitieses;
    }

}
