package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntityPricesId generated by hbm2java
 */
@Embeddable
public class EntityPricesId implements java.io.Serializable {

    private int id;
    private Date created;

    public EntityPricesId() {
    }

    public EntityPricesId(int id, Date created) {
        this.id = id;
        this.created = created;
    }

    @Column(name = "id", nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof EntityPricesId))
            return false;
        EntityPricesId castOther = (EntityPricesId) other;

        return (this.getId() == castOther.getId())
                && ((this.getCreated() == castOther.getCreated()) || (this
                        .getCreated() != null && castOther.getCreated() != null && this
                        .getCreated().equals(castOther.getCreated())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getId();
        result = 37 * result
                + (getCreated() == null ? 0 : this.getCreated().hashCode());
        return result;
    }

}
