package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntityClass generated by hbm2java
 */
@Entity
@Table(name = "entity_class", catalog = "agency")
public class EntityClass implements java.io.Serializable {

    private Integer id;
    private String name;
    private float minVal;
    private float maxVal;
    private Set<Entities> entitieses = new HashSet<Entities>(0);

    public EntityClass() {
    }

    public EntityClass(String name, float minVal, float maxVal) {
        this.name = name;
        this.minVal = minVal;
        this.maxVal = maxVal;
    }

    public EntityClass(String name, float minVal, float maxVal,
            Set<Entities> entitieses) {
        this.name = name;
        this.minVal = minVal;
        this.maxVal = maxVal;
        this.entitieses = entitieses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "min_val", nullable = false, precision = 12, scale = 0)
    public float getMinVal() {
        return this.minVal;
    }

    public void setMinVal(float minVal) {
        this.minVal = minVal;
    }

    @Column(name = "max_val", nullable = false, precision = 12, scale = 0)
    public float getMaxVal() {
        return this.maxVal;
    }

    public void setMaxVal(float maxVal) {
        this.maxVal = maxVal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "entityClass")
    public Set<Entities> getEntitieses() {
        return this.entitieses;
    }

    public void setEntitieses(Set<Entities> entitieses) {
        this.entitieses = entitieses;
    }

}
