package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MeasureImportances generated by hbm2java
 */
@Entity
@Table(name = "measure_importances", catalog = "agency")
public class MeasureImportances implements java.io.Serializable, IEntity<MeasureImportancesId> {

    private MeasureImportancesId id;
    private Measures measuresByMeasure1Id;
    private Measures measuresByMeasure2Id;
    private float importance;

    public MeasureImportances() {
    }

    public MeasureImportances(MeasureImportancesId id,
            Measures measuresByMeasure1Id, Measures measuresByMeasure2Id,
            float importance) {
        this.id = id;
        this.measuresByMeasure1Id = measuresByMeasure1Id;
        this.measuresByMeasure2Id = measuresByMeasure2Id;
        this.importance = importance;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "measure1Id", column = @Column(name = "measure_1_id", nullable = false)),
            @AttributeOverride(name = "measure2Id", column = @Column(name = "measure_2_id", nullable = false)) })
    public MeasureImportancesId getId() {
        return this.id;
    }

    public void setId(MeasureImportancesId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "measure_1_id", nullable = false, insertable = false, updatable = false)
    public Measures getMeasuresByMeasure1Id() {
        return this.measuresByMeasure1Id;
    }

    public void setMeasuresByMeasure1Id(Measures measuresByMeasure1Id) {
        this.measuresByMeasure1Id = measuresByMeasure1Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "measure_2_id", nullable = false, insertable = false, updatable = false)
    public Measures getMeasuresByMeasure2Id() {
        return this.measuresByMeasure2Id;
    }

    public void setMeasuresByMeasure2Id(Measures measuresByMeasure2Id) {
        this.measuresByMeasure2Id = measuresByMeasure2Id;
    }

    @Column(name = "importance", nullable = false, precision = 12, scale = 0)
    public float getImportance() {
        return this.importance;
    }

    public void setImportance(float importance) {
        this.importance = importance;
    }

}
