package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MeasureImportancesId generated by hbm2java
 */
@Embeddable
public class MeasureImportancesId implements java.io.Serializable {

    private Integer measure1Id;
    private Integer measure2Id;

    public MeasureImportancesId() {
    }

    public MeasureImportancesId(Integer measure1Id, Integer measure2Id) {
        this.measure1Id = measure1Id;
        this.measure2Id = measure2Id;
    }

    @Column(name = "measure_1_id", nullable = false)
    public Integer getMeasure1Id() {
        return this.measure1Id;
    }

    public void setMeasure1Id(Integer measure1Id) {
        this.measure1Id = measure1Id;
    }

    @Column(name = "measure_2_id", nullable = false)
    public Integer getMeasure2Id() {
        return this.measure2Id;
    }

    public void setMeasure2Id(Integer measure2Id) {
        this.measure2Id = measure2Id;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof MeasureImportancesId))
            return false;
        MeasureImportancesId castOther = (MeasureImportancesId) other;

        return (this.getMeasure1Id() == castOther.getMeasure1Id())
                && (this.getMeasure2Id() == castOther.getMeasure2Id());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMeasure1Id();
        result = 37 * result + this.getMeasure2Id();
        return result;
    }

}
