package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Norms generated by hbm2java
 */
@Entity
@Table(name = "norms", catalog = "agency")
public class Norms implements java.io.Serializable {

    private NormsId id;
    private Date changed;
    private float monthNorm;

    public Norms() {
    }

    public Norms(NormsId id, Date changed, float monthNorm) {
        this.id = id;
        this.changed = changed;
        this.monthNorm = monthNorm;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
            @AttributeOverride(name = "activityTypeId", column = @Column(name = "activity_type_id", nullable = false)) })
    public NormsId getId() {
        return this.id;
    }

    public void setId(NormsId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "changed", nullable = false, length = 10)
    public Date getChanged() {
        return this.changed;
    }

    public void setChanged(Date changed) {
        this.changed = changed;
    }

    @Column(name = "month_norm", nullable = false, precision = 12, scale = 0)
    public float getMonthNorm() {
        return this.monthNorm;
    }

    public void setMonthNorm(float monthNorm) {
        this.monthNorm = monthNorm;
    }

}
