package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NormsId generated by hbm2java
 */
@Embeddable
public class NormsId implements java.io.Serializable {

    private Integer id;
    private Integer activityTypeId;

    public NormsId() {
    }

    public NormsId(Integer id, Integer activityTypeId) {
        this.id = id;
        this.activityTypeId = activityTypeId;
    }

    @Column(name = "id", nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "activity_type_id", nullable = false)
    public Integer getActivityTypeId() {
        return this.activityTypeId;
    }

    public void setActivityTypeId(Integer activityTypeId) {
        this.activityTypeId = activityTypeId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof NormsId))
            return false;
        NormsId castOther = (NormsId) other;

        return (this.getId() == castOther.getId())
                && (this.getActivityTypeId() == castOther.getActivityTypeId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getId();
        result = 37 * result + this.getActivityTypeId();
        return result;
    }

}
