package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Norms generated by hbm2java
 */
@Entity
@Table(name = "norms", catalog = "agency")
public class Norms implements java.io.Serializable, IEntity<Integer> {

    private Integer activityTypeId;
    private Date changed;
    private Float monthNorm;

    public Norms() {
    }

    public Norms(Integer id, Date changed, Float monthNorm) {
        this.activityTypeId = id;
        this.changed = changed;
        this.monthNorm = monthNorm;
    }

    @Override
    @Id
    @Column(name = "activity_type_id", nullable = false)
    public Integer getId() {
        return this.activityTypeId;
    }

    @Override
    public void setId(Integer id) {
        this.activityTypeId = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "changed", nullable = false, length = 10)
    public Date getChanged() {
        return this.changed;
    }

    public void setChanged(Date changed) {
        this.changed = changed;
    }

    @Column(name = "month_norm", nullable = false, precision = 12, scale = 0)
    public Float getMonthNorm() {
        return this.monthNorm;
    }

    public void setMonthNorm(Float monthNorm) {
        this.monthNorm = monthNorm;
    }

}
