package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions", catalog = "agency")
public class Questions extends BaseEntity<Integer> implements java.io.Serializable, IEntity<Integer> {

    private Measures measures;
    private String text;
    private Set<EmployeeEvaluations> employeeEvaluationses = new HashSet<EmployeeEvaluations>(
            0);

    public Questions() {
    }

    public Questions(Measures measures, String text) {
        this.measures = measures;
        this.text = text;
    }

    public Questions(Measures measures, String text,
            Set<EmployeeEvaluations> employeeEvaluationses) {
        this.measures = measures;
        this.text = text;
        this.employeeEvaluationses = employeeEvaluationses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "measure_id", nullable = false)
    public Measures getMeasures() {
        return this.measures;
    }

    public void setMeasures(Measures measures) {
        this.measures = measures;
    }

    @Column(name = "text", nullable = false, length = 1000)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
    public Set<EmployeeEvaluations> getEmployeeEvaluationses() {
        return this.employeeEvaluationses;
    }

    public void setEmployeeEvaluationses(
            Set<EmployeeEvaluations> employeeEvaluationses) {
        this.employeeEvaluationses = employeeEvaluationses;
    }

}
