package com.realty.agency.domain;

// Generated Apr 1, 2013 12:12:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RatesId generated by hbm2java
 */
@Embeddable
public class RatesId implements java.io.Serializable {

    private Integer measureId;
    private Integer employeeId;
    private Date created;

    public RatesId() {
    }

    public RatesId(Integer measureId, Integer employeeId, Date created) {
        this.measureId = measureId;
        this.employeeId = employeeId;
        this.created = created;
    }

    @Column(name = "measure_id", nullable = false)
    public Integer getMeasureId() {
        return this.measureId;
    }

    public void setMeasureId(Integer measureId) {
        this.measureId = measureId;
    }

    @Column(name = "employee_id", nullable = false)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RatesId))
            return false;
        RatesId castOther = (RatesId) other;

        return (this.getMeasureId() == castOther.getMeasureId())
                && (this.getEmployeeId() == castOther.getEmployeeId())
                && ((this.getCreated() == castOther.getCreated()) || (this
                        .getCreated() != null && castOther.getCreated() != null && this
                        .getCreated().equals(castOther.getCreated())));
    }

    public int hashCode() {
        Integer result = 17;

        result = 37 * result + this.getMeasureId();
        result = 37 * result + this.getEmployeeId();
        result = 37 * result
                + (getCreated() == null ? 0 : this.getCreated().hashCode());
        return result;
    }

}
